apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: your-namespace
  labels:
    app: fluentd
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match **>
      @type elasticsearch
      @log_level info
      host "${ELASTICSEARCH_HOST}"
      port "${ELASTICSEARCH_PORT}"
      scheme https
      user "${ELASTICSEARCH_USER}"
      password "${ELASTICSEARCH_PASSWORD}"
      ssl_verify false
      logstash_format true
      logstash_prefix your-log-prefix
      logstash_dateformat %Y.%m.%d
      include_tag_key true
      tag_key @log_name
      type_name _doc
      buffer_chunk_limit 2M
      buffer_queue_limit 8
      flush_interval 5s
      retry_limit 3
      disable_retry_limit false
      num_threads 1
    </match>
